export interface ReleaseDateFields {
  publish_on?: string | Date | null;
  published_at?: string | Date | null;
}

export function releaseSourceDate(item: ReleaseDateFields): Date | null {
  const value = item.publish_on || item.published_at;
  if (!value) return null;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? null : date;
}

export function localReleaseDate(item: ReleaseDateFields): Date | null {
  const date = releaseSourceDate(item);
  if (!date) return null;

  // Essays may be generated by the Saturday cron, but the publication's
  // release day is always Monday. Derive that boundary entirely from the
  // reader's local calendar: `getDay`, `setDate`, and the Date constructor
  // all use local time. This intentionally does not use UTC, so the essay
  // appears at 00:00 on Monday wherever the reader is.
  const release = new Date(date.getFullYear(), date.getMonth(), date.getDate());
  const daysUntilMonday = (8 - release.getDay()) % 7;
  release.setDate(release.getDate() + daysUntilMonday);
  return release;
}

export function isReleasedLocally(item: ReleaseDateFields, now = new Date()): boolean {
  const release = localReleaseDate(item);
  return release ? release.getTime() <= now.getTime() : true;
}

export function startOfToday(from = new Date()): Date {
  return new Date(from.getFullYear(), from.getMonth(), from.getDate());
}

export function thisOrNextMonday(from = new Date()): Date {
  const d = startOfToday(from);
  const days = (8 - d.getDay()) % 7;
  d.setDate(d.getDate() + days);
  return d;
}

export function nextMondayAfter(from = new Date()): Date {
  const d = startOfToday(from);
  const days = (8 - d.getDay()) % 7 || 7;
  d.setDate(d.getDate() + days);
  return d;
}
