export interface ReleaseDateFields {
  publish_on?: string | Date | null;
  published_at?: string | Date | null;
}

export function releaseSourceDate(item: ReleaseDateFields): Date | null {
  const value = item.publish_on || item.published_at;
  if (!value) return null;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? null : date;
}

export function localReleaseDate(item: ReleaseDateFields): Date | null {
  const date = releaseSourceDate(item);
  if (!date) return null;

  // Essays may be generated by the Saturday cron, but the publication's
  // release day is always Monday. Derive that boundary entirely from the
  // reader's local calendar: `getDay`, `setDate`, and the Date constructor
  // all use local time. This intentionally does not use UTC, so the essay
  // appears at 00:00 on Monday wherever the reader is.
  const release = new Date(date.getFullYear(), date.getMonth(), date.getDate());
  const daysUntilMonday = (8 - release.getDay()) % 7;
  release.setDate(release.getDate() + daysUntilMonday);
  return release;
}

export function isReleasedLocally(item: ReleaseDateFields, now = new Date()): boolean {
  const release = localReleaseDate(item);
  return release ? release.getTime() <= now.getTime() : true;
}

/**
 * True once local midnight Monday has passed in *every* timezone, not just the
 * server's. Reader clocks span UTC+14 to UTC-12, and the server's own offset is
 * somewhere in that range too, so the last reader crosses the boundary at most
 * 26h after `localReleaseDate` computed here.
 *
 * Anything older than that is safe to render server-side: no reader anywhere
 * can still be waiting for it. That matters because crawlers, link previews and
 * article importers only ever see the server HTML.
 */
export function isReleasedEverywhere(item: ReleaseDateFields, now = new Date()): boolean {
  const release = localReleaseDate(item);
  if (!release) return true;
  return release.getTime() + 26 * 60 * 60 * 1000 <= now.getTime();
}

export function startOfToday(from = new Date()): Date {
  return new Date(from.getFullYear(), from.getMonth(), from.getDate());
}

export function thisOrNextMonday(from = new Date()): Date {
  const d = startOfToday(from);
  const days = (8 - d.getDay()) % 7;
  d.setDate(d.getDate() + days);
  return d;
}

export function nextMondayAfter(from = new Date()): Date {
  const d = startOfToday(from);
  const days = (8 - d.getDay()) % 7 || 7;
  d.setDate(d.getDate() + days);
  return d;
}
